apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app-deployment
spec:
  selector:
    matchLabels:
      app: express-app-pod
  template:
    metadata:
      labels:
        app: express-app-pod
    spec:
      containers:
      - name: express-app-container
        image: hseymo/express-app:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
